name: ci

on:
  - push
  - pull_request

jobs:

  build:
    container:
      image: ubuntu-latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
    - name: ğŸ‹ Build the Docker image
      run: docker build . --file Dockerfile --tag ov_wag:$(date +%s)
    - name: â˜‘ï¸ Run Tests
      run: ./ov test
